import {
	LOADING_SCREEN_COMPANY_LOGO_CONFIG,
	LOADING_SCREEN_CONTAINER,
	LOADING_SCREEN_GAME_RELATED_IMAGE_CONFIG,
	LOADING_SCREEN_PROGRESS_BAR_CONFIG,
	LOADING_SCREEN_PROGRESS_BAR_SHADOW_CONFIG,
	LOADING_SCREEN_PROGRESS_BOX_CONFIG,
	LOADING_SCREEN_PROGRESS_LINE_CONTAINER_CONFIG
} from "@data";
import {ILoadingScreenCreationConfig} from "@profair/core";

export class LoadingScreenCreationConfig implements ILoadingScreenCreationConfig {
	public x = LOADING_SCREEN_CONTAINER.x;
	public y = LOADING_SCREEN_CONTAINER.y;
	public creationData = {
		gameRelatedImageConfig: LOADING_SCREEN_GAME_RELATED_IMAGE_CONFIG,
		progressLineContainerConfig: LOADING_SCREEN_PROGRESS_LINE_CONTAINER_CONFIG,
		progressBoxConfig: LOADING_SCREEN_PROGRESS_BOX_CONFIG,
		progressBarConfig: LOADING_SCREEN_PROGRESS_BAR_CONFIG,
		progressBarShadowConfig: LOADING_SCREEN_PROGRESS_BAR_SHADOW_CONFIG,
		companyLogoConfig: LOADING_SCREEN_COMPANY_LOGO_CONFIG
	};
}
