export enum EAnimationData {
	POPUP_ANIMATION_TIME = 2022,
	WIN_VALUE_ANIMATION_DURATION = 170,
	STOP_TIME = 1100,
	CONTINUE_TEXT_ANIMATION_DELAYING = 1300,
	SHOW_TEXT_ANIMATION_DURATION = 300,
	TWEEN_PULSE_ANIMATION_DURATION = 800
}
